name: Merge Branches

on:
  workflow_dispatch:
    inputs:
      projectId:
        description: 'Project ID to fetch data for'
        required: true
        default: 'defaultProjectId'

  pull_request:
    types:
      - closed  # Runs when a PR is merged
          
permissions:
  contents: write

jobs:
  merge_branches:
    if: github.event.pull_request.merged == true  # Ensures it runs only on merge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check for First Commit
        run: |
          FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
          echo "First commit hash: $FIRST_COMMIT"
          echo "Current commit hash: $GITHUB_SHA"
          if [[ "$FIRST_COMMIT" == "$GITHUB_SHA" ]]; then
            echo "Skipping workflow because this is the first commit."
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Extract Version
        run: |
          VERSION=$(cat version.yaml | awk -F'=' '{print $2}' | awk -F'.' '{print $1}')
          echo "Extracted major version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV


      - name: Get Branch Name
        run: echo "BASE_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
      
      - name: Merge Changes
        env:
           DIGIA_TOKEN: ${{ secrets.DIGIA_TOKEN }}
           BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          echo "$BASE_BRANCH"
          curl -o merge_changes.sh "https://raw.githubusercontent.com/Digia-Technology-Private-Limited/digia_public_scripts_dev/refs/heads/main/github/version/$VERSION/merge_changes.sh"
          chmod +x merge_changes.sh
          ./merge_changes.sh "$BASE_BRANCH" "$VERSION"


